spring:
  datasource:
    password: tIjodGiLTBlUwOjRJwdXYdRZDQHeJweA
    url: jdbc:mysql://viaduct.proxy.rlwy.net:37162/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
